#!/usr/bin/env python3
"""Make a simple AIR (ambiguous interaction restraints) file for HADDOCK.

Usage examples:
  python make_air.py --act-rec 45 48 52 --act-lig 101 105 \
    --seg-rec A --seg-lig B --atom-rec CA --atom-lig CA \
    --out ../restraints/air.tbl

For small molecules, set --atom-lig to a specific atom (e.g., C1) or keep CA as a placeholder and edit manually.
"""
import argparse
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--act-rec', nargs='+', type=int, required=True,
                   help='Active residues on receptor')
    p.add_argument('--act-lig', nargs='+', type=int, required=True,
                   help='Active residues on ligand/partner')
    p.add_argument('--seg-rec', default='A', help='Segid for receptor (default A)')
    p.add_argument('--seg-lig', default='B', help='Segid for ligand/partner (default B)')
    p.add_argument('--atom-rec', default='CA', help='Atom name for receptor restraint (default CA)')
    p.add_argument('--atom-lig', default='CA', help='Atom name for ligand restraint (default CA)')
    p.add_argument('--target', type=float, default=2.0, help='Target distance (Å)')
    p.add_argument('--lower', type=float, default=2.0, help='Lower bound (Å)')
    p.add_argument('--upper', type=float, default=0.0, help='Upper bound (Å)')
    p.add_argument('--out', type=Path, default=Path('../restraints/air.tbl'),
                   help='Output AIR file path')
    return p.parse_args()


def main():
    args = parse_args()
    lines = ["! Generated by make_air.py", "! assign (atom1) (atom2) target lower upper"]
    for r in args.act_rec:
        for l in args.act_lig:
            lines.append(
                "assign (segid {seg1} and resid {r} and name {a1})\n"
                "       (segid {seg2} and resid {l} and name {a2})\n"
                "       {t:.2f} {lo:.2f} {up:.2f}".format(
                    seg1=args.seg_rec, r=r, a1=args.atom_rec,
                    seg2=args.seg_lig, l=l, a2=args.atom_lig,
                    t=args.target, lo=args.lower, up=args.upper,
                )
            )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.out} with {len(lines)-2} restraints")


if __name__ == '__main__':
    main()
